### IMPORTS
## Color schemes
import:
  # - ~/.config/alacritty/themes/catppuccin.yml
  # - ~/.config/alacritty/themes/dracula.yml
  # - ~/.config/alacritty/themes/gruvbox.yml
  # - ~/.config/alacritty/themes/nord.yml
  - ~/.config/alacritty/themes/spacegray.yml

### SETTINGS
env:
  TERM: xterm-256color
window:
  padding:
    x: 6
    y: 6
  dynamic_padding: false
  opacity: 1.0
  title: Alacritty
  class:
    instance: Alacritty
    general: Alacritty
scrolling:
  history: 5000
font:
  normal:
    family: JetBrainsMono Nerd Font
    # family: Mononoki Nerd Font
    style: Regular
  bold:
    family: JetBrainsMono Nerd Font
    # family: Mononoki Nerd Font
    style: Bold
  italic:
    family: JetBrainsMono Nerd Font
    # family: Mononoki Nerd Font
    style: Italic
  bold_italic:
    family: JetBrainsMono Nerd Font
    # family: Mononoki Nerd Font
    style: Bold Italic
  size: 10.0
  offset:
    x: 0
    y: 1
draw_bold_text_with_bright_colors: true
key_bindings:
  - { key: V,         mods: Control|Shift, action: Paste                       }
  - { key: C,         mods: Control|Shift, action: Copy                        }
  - { key: Insert,    mods: Shift,         action: PasteSelection              }
  - { key: Key0,      mods: Control,       action: ResetFontSize               }
  - { key: Equals,    mods: Control,       action: IncreaseFontSize            }
  - { key: Plus,      mods: Control,       action: IncreaseFontSize            }
  - { key: Minus,     mods: Control,       action: DecreaseFontSize            }
  - { key: F11,       mods: None,          action: ToggleFullscreen            }
  - { key: Paste,     mods: None,          action: Paste                       }
  - { key: Copy,      mods: None,          action: Copy                        }
  - { key: L,         mods: Control,       action: ClearLogNotice              }
  - { key: L,         mods: Control,       chars: "\x0c"                       }
  - { key: PageUp,    mods: None,          action: ScrollPageUp,   mode: ~Alt  }
  - { key: PageDown,  mods: None,          action: ScrollPageDown, mode: ~Alt  }
  - { key: Home,      mods: Shift,         action: ScrollToTop,    mode: ~Alt  }
  - { key: End,       mods: Shift,         action: ScrollToBottom, mode: ~Alt  }
