#     ____   ____ ______ ____   __  ___ #
#    / __ \ /  _// ____// __ \ /  |/  / #
#   / /_/ / / / / /    / / / // /|_/ /  #
#  / ____/_/ / / /___ / /_/ // /  / /   #
# /_/    /___/ \____/ \____//_/  /_/    #


# General
backend = "xrender"
vsync = true;
use-damage = true;
corner-radius = 5.0;

# Fading
fading = true;
fade-in-step = 0.025;
fade-out-step = 0.025;
fade-delta = 8
fade-exclude = [];

# Shadow
shadow = true;
shadow-radius = 9;
shadow-opacity = .80;
shadow-offset-x = -12;
shadow-offset-y = -12;
shadow-exclude = [];

# Animations
animations = (
  {
    triggers = ["open", "show"];
    preset = "appear";
    duration = 0.20;
  },
  {
    triggers = ["close", "hide"];
    preset = "disappear";
    duration = 0.20;
  },
  {
    triggers = ["geometry"];
    preset = "geometry-change";
    duration = 0.30;
  }
);