general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

listener {
    timeout = 120
    on-timeout = brightnessctl --device=intel_backlight -s set 10%
    on-resume = brightnessctl --device=intel_backlight -s set 40%
}

listener {
    timeout = 200
    on-timeout = loginctl lock-session
}

listener {
    timeout = 250
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' && brightnessctl --device=intel_backlight -s set 40%
}

listener {
    timeout = 1800
    on-timeout = systemctl suspend
}

# MANGO
# listener {
#     timeout = 330
#     on-timeout = mmsg -d disable_monitor,eDP-2
#     on-resume = mmsg -d enable_monitor,eDP-2
# }

# listener {
#     timeout = 330
#     on-timeout = mmsg -d disable_monitor,HDMI-A-1
#     on-resume = mmsg -d enable_monitor,HDMI-A-1
# }
