# exec=pkill swaybg; swaybg -m fill -i ~/.dotfiles/wallpapers/everforest.png &
exec=pkill swaybg; swaybg -m fill -i $(shuf -e -n1 $HOME/Obrazy/wallpapers/everforest/*) &

rootcolor=0x1e2326ff
bordercolor=0x272e33ff
focuscolor=0xa7c080ff
maximizescreencolor=0xa7c080ff
urgentcolor=0xa7c080ff
scratchpadcolor=0xa7c080ff
globalcolor=0xa7c080ff
overlaycolor=0xa7c080ff