# exec=pkill swaybg; swaybg -m fill -i ~/.dotfiles/wallpapers/grayscale.png &
exec=pkill swaybg; swaybg -m fill -i $(shuf -e -n1 $HOME/Obrazy/wallpapers/grayscale/*) &

rootcolor=0x373737ff
bordercolor=0x727272ff
focuscolor=0xE1E1E1ff
maximizescreencolor=0xE1E1E1ff
urgentcolor=0xE1E1E1ff
scratchpadcolor=0xE1E1E1ff
globalcolor=0xE1E1E1ff
overlaycolor=0xE1E1E1ff
