exec=pkill swaybg; swaybg -i ~/.dotfiles/wallpapers/nvim-alt.png &

rootcolor=0x1a212dff
bordercolor=0x303742ff
focuscolor=0xaaedb7ff
maximizescreencolor=0xaaedb7ff
urgentcolor=0xaaedb7ff
scratchpadcolor=0xaaedb7ff
globalcolor=0xaaedb7ff
overlaycolor=0xaaedb7ff
