#!/usr/bin/env bash

set -e
set -u


Wallpaper () {
if [ $XDG_SESSION_TYPE = 'wayland' ]; then
  directory=/home/$USER/Obrazy/tapety/
  if [ -d "$directory" ]; then
    random_background=$(ls $directory/* | shuf -n 1)
    hyprctl hyprpaper unload all
    hyprctl hyprpaper preload $random_background
    hyprctl hyprpaper wallpaper ", $random_background"
  fi
elif [ $XDG_SESSION_TYPE = 'x11' ]; then
  shuf -e -n1 $HOME/Obrazy/tapety/* | xargs feh --bg-fill
else
  echo "What?"
fi
}

Themes () {
  catppuccin () {
    bash <(curl -s https://raw.githubusercontent.com/ch1ebak/postinstall-script/refs/heads/main/scripts/themes/scripts/catppuccin.sh)
  }
  dracula () {
    bash <(curl -s https://raw.githubusercontent.com/ch1ebak/postinstall-script/refs/heads/main/scripts/themes/scripts/dracula.sh)
  }
  everforest () {
    bash <(curl -s https://raw.githubusercontent.com/ch1ebak/postinstall-script/refs/heads/main/scripts/themes/scripts/everforest.sh)
  }
  grayscale () {
    bash <(curl -s https://raw.githubusercontent.com/ch1ebak/postinstall-script/refs/heads/main/scripts/themes/scripts/grayscale.sh)
  }
  gruvbox () {
    bash <(curl -s https://raw.githubusercontent.com/ch1ebak/postinstall-script/refs/heads/main/scripts/themes/scripts/gruvbox.sh)
  }
  kanagawa () {
    bash <(curl -s https://raw.githubusercontent.com/ch1ebak/postinstall-script/refs/heads/main/scripts/themes/scripts/kanagawa.sh)
  }
  spacegray () {
    bash <(curl -s https://raw.githubusercontent.com/ch1ebak/postinstall-script/refs/heads/main/scripts/themes/scripts/spacegray.sh)
  }
  tokyonight () {
    bash <(curl -s https://raw.githubusercontent.com/ch1ebak/postinstall-script/refs/heads/main/scripts/themes/scripts/tokyonight.sh)
  }
  declare -a options=(
  catppuccin
  dracula
  everforest
  grayscale
  gruvbox
  kanagawa
  spacegray
  tokyonight
  "quit"
  )
  choice=$(printf '%s\n' "${options[@]}" | rofi -m 1 -dmenu -i -l 20 -p 'Utilities')
  if [[ "$choice" == quit ]]; then
    echo "Program Terminated." && exit 1
  elif [ "$choice" ]; then
    cfg=$(printf '%s\n' "${choice}" | awk '{print $NF}')
    "$cfg"
  else
    echo "What?" && exit 1
  fi
}

Screenshot () {
if [ $XDG_SESSION_TYPE = 'wayland' ]; then
  sleep 1; grim -o HDMI-A-1 -l 9 -t png
  notify-send "Screenshot Taken"
elif [ $XDG_SESSION_TYPE = 'x11' ]; then
  scrot -d 1 -M 0 -q 9
  notify-send "Screenshot Taken"
else
  echo "What?"
fi
}

Reload () {
if [ $XDG_SESSION_TYPE = 'wayland' ]; then
  nohup bash -c "killall -e hyprpaper & sleep 1; hyprpaper &"
  nohup bash -c "killall waybar && waybar & disown"
elif [ $XDG_SESSION_TYPE = 'x11' ]; then
  qtile cmd-obj -o cmd -f reload_config
else
  echo "What?"
fi
}


declare -a options=(
Screenshot
Wallpaper
Themes
Reload
"Quit"
)

choice=$(printf '%s\n' "${options[@]}" | rofi -m 1 -dmenu -i -l 20 -p 'Utilities')

if [[ "$choice" == quit ]]; then
	echo "Program Terminated." && exit 1
elif [ "$choice" ]; then
	cfg=$(printf '%s\n' "${choice}" | awk '{print $NF}')
	"$cfg"
else
	echo "Program Terminated." && exit 1
fi
